"""new note fields

Revision ID: 2d39a097d0a1
Revises: 5b646ebe8d77
Create Date: 2025-06-23 13:15:10.789494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d39a097d0a1'
down_revision = '5b646ebe8d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('green_decor', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_column('green_decor')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
