"""pots table

Revision ID: 3adaaf2c8e3a
Revises: 
Create Date: 2025-06-20 08:42:14.166733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adaaf2c8e3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clay', sa.String(length=60), nullable=True),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pot')
    # ### end Alembic commands ###
