"""glaze table

Revision ID: 5b646ebe8d77
Revises: 3adaaf2c8e3a
Create Date: 2025-06-20 09:57:45.728006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b646ebe8d77'
down_revision = '3adaaf2c8e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glaze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('pot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pot_id'], ['pot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glaze_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_glaze_pot_id'), ['pot_id'], unique=False)

    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('throw_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('clay_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thrown_height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thrown_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thrown_notes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('trim_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('trim_notes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('glaze_notes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('finished_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('finished_height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('finished_notes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_column('finished_notes')
        batch_op.drop_column('finished_height')
        batch_op.drop_column('finished_width')
        batch_op.drop_column('glaze_notes')
        batch_op.drop_column('trim_notes')
        batch_op.drop_column('trim_date')
        batch_op.drop_column('thrown_notes')
        batch_op.drop_column('thrown_width')
        batch_op.drop_column('thrown_height')
        batch_op.drop_column('clay_weight')
        batch_op.drop_column('throw_date')

    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glaze_pot_id'))
        batch_op.drop_index(batch_op.f('ix_glaze_name'))

    op.drop_table('glaze')
    # ### end Alembic commands ###
